pipeline{
    agent any;

    tools{
        maven 'Maven';
        jdk 'JDK11';
    }

    stages {
        stage('Cloning'){
            steps {
                git(
                    url: 'https://git.epam.com/maksim_yurau/jenkins-demo' ,
                    branch: 'develop'
                )

            }
        }
        stage('Building'){
            steps{
                bat 'mvn clean install'
            }
        }
    }
}